// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: gorm.proto

package gorm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GormOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orm bool `protobuf:"varint,1,opt,name=orm,proto3" json:"orm,omitempty"`
}

func (x *GormOptions) Reset() {
	*x = GormOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GormOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GormOptions) ProtoMessage() {}

func (x *GormOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gorm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GormOptions.ProtoReflect.Descriptor instead.
func (*GormOptions) Descriptor() ([]byte, []int) {
	return file_gorm_proto_rawDescGZIP(), []int{0}
}

func (x *GormOptions) GetOrm() bool {
	if x != nil {
		return x.Orm
	}
	return false
}

type GormType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*GormType_Primary
	//	*GormType_AutoIncrement
	//	*GormType_Index
	//	*GormType_NotNull
	//	*GormType_UniqueIndex
	Type isGormType_Type `protobuf_oneof:"type"`
}

func (x *GormType) Reset() {
	*x = GormType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GormType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GormType) ProtoMessage() {}

func (x *GormType) ProtoReflect() protoreflect.Message {
	mi := &file_gorm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GormType.ProtoReflect.Descriptor instead.
func (*GormType) Descriptor() ([]byte, []int) {
	return file_gorm_proto_rawDescGZIP(), []int{1}
}

func (m *GormType) GetType() isGormType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *GormType) GetPrimary() bool {
	if x, ok := x.GetType().(*GormType_Primary); ok {
		return x.Primary
	}
	return false
}

func (x *GormType) GetAutoIncrement() bool {
	if x, ok := x.GetType().(*GormType_AutoIncrement); ok {
		return x.AutoIncrement
	}
	return false
}

func (x *GormType) GetIndex() bool {
	if x, ok := x.GetType().(*GormType_Index); ok {
		return x.Index
	}
	return false
}

func (x *GormType) GetNotNull() bool {
	if x, ok := x.GetType().(*GormType_NotNull); ok {
		return x.NotNull
	}
	return false
}

func (x *GormType) GetUniqueIndex() bool {
	if x, ok := x.GetType().(*GormType_UniqueIndex); ok {
		return x.UniqueIndex
	}
	return false
}

type isGormType_Type interface {
	isGormType_Type()
}

type GormType_Primary struct {
	Primary bool `protobuf:"varint,1,opt,name=primary,proto3,oneof"`
}

type GormType_AutoIncrement struct {
	AutoIncrement bool `protobuf:"varint,2,opt,name=auto_increment,json=autoIncrement,proto3,oneof"`
}

type GormType_Index struct {
	Index bool `protobuf:"varint,3,opt,name=index,proto3,oneof"`
}

type GormType_NotNull struct {
	NotNull bool `protobuf:"varint,4,opt,name=not_null,json=notNull,proto3,oneof"`
}

type GormType_UniqueIndex struct {
	UniqueIndex bool `protobuf:"varint,5,opt,name=unique_index,json=uniqueIndex,proto3,oneof"`
}

func (*GormType_Primary) isGormType_Type() {}

func (*GormType_AutoIncrement) isGormType_Type() {}

func (*GormType_Index) isGormType_Type() {}

func (*GormType_NotNull) isGormType_Type() {}

func (*GormType_UniqueIndex) isGormType_Type() {}

type GormRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Ref:
	//
	//	*GormRef_BelongsTo
	Ref isGormRef_Ref `protobuf_oneof:"ref"`
}

func (x *GormRef) Reset() {
	*x = GormRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GormRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GormRef) ProtoMessage() {}

func (x *GormRef) ProtoReflect() protoreflect.Message {
	mi := &file_gorm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GormRef.ProtoReflect.Descriptor instead.
func (*GormRef) Descriptor() ([]byte, []int) {
	return file_gorm_proto_rawDescGZIP(), []int{2}
}

func (m *GormRef) GetRef() isGormRef_Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (x *GormRef) GetBelongsTo() *BelongsTo {
	if x, ok := x.GetRef().(*GormRef_BelongsTo); ok {
		return x.BelongsTo
	}
	return nil
}

type isGormRef_Ref interface {
	isGormRef_Ref()
}

type GormRef_BelongsTo struct {
	BelongsTo *BelongsTo `protobuf:"bytes,1,opt,name=belongs_to,json=belongsTo,proto3,oneof"`
}

func (*GormRef_BelongsTo) isGormRef_Ref() {}

type BelongsTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BelongsTo) Reset() {
	*x = BelongsTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BelongsTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BelongsTo) ProtoMessage() {}

func (x *BelongsTo) ProtoReflect() protoreflect.Message {
	mi := &file_gorm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BelongsTo.ProtoReflect.Descriptor instead.
func (*BelongsTo) Descriptor() ([]byte, []int) {
	return file_gorm_proto_rawDescGZIP(), []int{3}
}

func (x *BelongsTo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BelongsTo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var file_gorm_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*GormOptions)(nil),
		Field:         2025,
		Name:          "gorm.opts",
		Tag:           "bytes,2025,opt,name=opts",
		Filename:      "gorm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*GormRef)(nil),
		Field:         2027,
		Name:          "gorm.ref",
		Tag:           "bytes,2027,opt,name=ref",
		Filename:      "gorm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*GormType)(nil),
		Field:         2026,
		Name:          "gorm.type",
		Tag:           "bytes,2026,opt,name=type",
		Filename:      "gorm.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional gorm.GormOptions opts = 2025;
	E_Opts = &file_gorm_proto_extTypes[0]
	// optional gorm.GormRef ref = 2027;
	E_Ref = &file_gorm_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional gorm.GormType type = 2026;
	E_Type = &file_gorm_proto_extTypes[2]
)

var File_gorm_proto protoreflect.FileDescriptor

var file_gorm_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x6f,
	0x72, 0x6d, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x0b, 0x47, 0x6f, 0x72, 0x6d, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x6f, 0x72, 0x6d, 0x22, 0xb1, 0x01, 0x0a, 0x08, 0x47, 0x6f, 0x72, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x27,
	0x0a, 0x0e, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1b, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x4e, 0x75, 0x6c, 0x6c, 0x12, 0x23, 0x0a, 0x0c,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x42, 0x0a, 0x07, 0x47, 0x6f, 0x72,
	0x6d, 0x52, 0x65, 0x66, 0x12, 0x30, 0x0a, 0x0a, 0x62, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x73, 0x5f,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x72, 0x6d, 0x2e,
	0x42, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x62, 0x65, 0x6c,
	0x6f, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x22, 0x31, 0x0a,
	0x09, 0x42, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x3a, 0x47, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe9, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x67, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x6f, 0x72, 0x6d, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x3a, 0x41, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xeb, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x6f, 0x72, 0x6d, 0x2e,
	0x47, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x3a, 0x42, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xea, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x72,
	0x6d, 0x2e, 0x47, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x73, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x72, 0x6d, 0x42, 0x09, 0x47, 0x6f,
	0x72, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x74, 0x64, 0x61, 0x6b, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x72, 0x6d, 0x2d, 0x64,
	0x61, 0x6f, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x04,
	0x47, 0x6f, 0x72, 0x6d, 0xca, 0x02, 0x04, 0x47, 0x6f, 0x72, 0x6d, 0xe2, 0x02, 0x10, 0x47, 0x6f,
	0x72, 0x6d, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x04, 0x47, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gorm_proto_rawDescOnce sync.Once
	file_gorm_proto_rawDescData = file_gorm_proto_rawDesc
)

func file_gorm_proto_rawDescGZIP() []byte {
	file_gorm_proto_rawDescOnce.Do(func() {
		file_gorm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gorm_proto_rawDescData)
	})
	return file_gorm_proto_rawDescData
}

var file_gorm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gorm_proto_goTypes = []interface{}{
	(*GormOptions)(nil),                 // 0: gorm.GormOptions
	(*GormType)(nil),                    // 1: gorm.GormType
	(*GormRef)(nil),                     // 2: gorm.GormRef
	(*BelongsTo)(nil),                   // 3: gorm.BelongsTo
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
}
var file_gorm_proto_depIdxs = []int32{
	3, // 0: gorm.GormRef.belongs_to:type_name -> gorm.BelongsTo
	4, // 1: gorm.opts:extendee -> google.protobuf.MessageOptions
	4, // 2: gorm.ref:extendee -> google.protobuf.MessageOptions
	5, // 3: gorm.type:extendee -> google.protobuf.FieldOptions
	0, // 4: gorm.opts:type_name -> gorm.GormOptions
	2, // 5: gorm.ref:type_name -> gorm.GormRef
	1, // 6: gorm.type:type_name -> gorm.GormType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	4, // [4:7] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gorm_proto_init() }
func file_gorm_proto_init() {
	if File_gorm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gorm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GormOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gorm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GormType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gorm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GormRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gorm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BelongsTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gorm_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GormType_Primary)(nil),
		(*GormType_AutoIncrement)(nil),
		(*GormType_Index)(nil),
		(*GormType_NotNull)(nil),
		(*GormType_UniqueIndex)(nil),
	}
	file_gorm_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*GormRef_BelongsTo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gorm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_gorm_proto_goTypes,
		DependencyIndexes: file_gorm_proto_depIdxs,
		MessageInfos:      file_gorm_proto_msgTypes,
		ExtensionInfos:    file_gorm_proto_extTypes,
	}.Build()
	File_gorm_proto = out.File
	file_gorm_proto_rawDesc = nil
	file_gorm_proto_goTypes = nil
	file_gorm_proto_depIdxs = nil
}
